### ISSUE TITLE
Download of lineas_limite.zip fails

### ISSUE THREAD

**Issue by ale0xb** [martgnz/es-atlas#1]
Seems like they changed the downloads center at cnig.es and [this link](http://centrodedescargas.cnig.es/CentroDescargas/equipamiento/lineas_limite.zip) seems to be  dead. 
A license agreement must be accepted by users before downloading any content from the website like shown in the following pic:

<img width="1362" alt="screen shot 2017-04-07 at 12 57 55" src="https://cloud.githubusercontent.com/assets/412841/24797655/81204c62-1b92-11e7-99ad-4be56ec96dba.png">

**Comment by martgnz** [comment]
Thanks for filling this issue.

I am looking for some ways around it, first by contacting them. If this doesn't work and they don't provide a proper download link, I'll probably have to make a mirror like [this one](https://github.com/martgnz/bcn-shp-zip).

**Comment by martgnz** [comment]
So I got a reply and they do publish an [open feed](http://www.ign.es/atom/ds.es.xml), but it uses [GML](https://en.wikipedia.org/wiki/Geography_Markup_Language) (it seems like a XML derivative, didn't find any simple way to convert it), so I just made a [repo with the zip file](https://github.com/martgnz/es-shp-zip). Now the script should download from the hosted file.

Sorry for taking so long, I got a bit busy last week.

**Comment by ale0xb** [comment]
Great work! 
Glad to know you were able to work it out. Quite shameful they no longer provide direct links to these files. The only problem I see with this approach is that we'll miss updates on the original file (but I don't think they occur so often and thus I agree it's not worth the effort to find more obscure ways to download it). 
Thank you!

**Comment by martgnz** [comment]
They seem to update the file every year, that's the time-frame which the INE seems to be applying to reflect the new municipalities, merges and so on ([more info here](http://www.ine.es/jaxi/menu.do?type=pcaxis&path=/t20/e245/codmun&file=inebase)).

I think it's fairly realistic to keep it in sync annually :)

**Comment by martgnz** [comment]
Happy to comment that @inigoflores has found a way to download the zip from the official servers in https://github.com/codeforspain/ds-limites-administrativos/pull/6. I just changed the url on this script so the files should be always updated.
