### ISSUE TITLE
add_names fails: autonomous_regions and provinces names are missing from municipalities.json

### ISSUE THREAD

**Issue by abubelinha** [martgnz/es-atlas#13]
I edited _package.json_ file and changed _config.add_names_ parameter from `false` to `true`
Then, after running `npm install`, everything worked: no errors.
An _/es_ folder was generated, which contains 3 json files, which I tried to visualize separately into [mapshaper.org](https://mapshaper.org):
 1. _autonomous_regions.json_ works: it contains _border_ and _autonomous_regions_ layers, and feature names are shown on hovering mouse over regions.
 2. _provinces.json_ works like the previous file, but contains also a _provinces_ layer, with their names shown on hovering as well.
 3. But **_municipalities.json_ doesn't work**: it contains also a _municipalities_ layer, with their names shown on hovering. The other two previous layers (_autonomous_regions_ and _provinces_) are still present, BUT in this file they DON'T show names (I only see F.ID value on hovering each feature).

**Comment by martgnz** [comment]
Yeah, this is a known limitation of the way we do the dissolving. We compute the polygons for provincias and comunidades directly from the municipios to share the borders. As a consequence those layers don't have names: the municipios don't have data for other administrative levels.

A better way would be to extract the feature names of every shapefile at the beginning and at the end merge them for every layer. This should be possible with mapshaper but I am not sure if I want to add it as a dependency, it's quite big compared to the topojson server.

**Comment by abubelinha** [comment]
Thanks for your answer.  

So, what I should do is to parse the _municipalities.json_ file with whatever other software (i.e. Python), check feature "id" values in layers _provinces_ and _autonomous_regions_ against a table containing id & toponyms, then add a `"properties":{"name":"feature_toponym"}` to each Feature in those layers, and then save the modified json file.
Correct?

**Comment by martgnz** [comment]
I found a less disruptive way to do it and released [0.5.0](https://github.com/martgnz/es-atlas/releases/tag/v0.5.0), which fixes this. Thanks for your patience!

**Comment by abubelinha** [comment]
Thanks.
So `add_names` option (formerly called `with_names`) is not available/needed anymore in `package.json` configuration file, right?

**Comment by martgnz** [comment]
No, it isn't. If you don't want names you can overwrite the files with a blank properties object like it's done here: https://github.com/martgnz/es-atlas/blob/master/properties.js#L77
