### ISSUE TITLE
Ability to generate data for certain regions

### ISSUE THREAD

**Issue by ale0xb** [martgnz/es-atlas#7]
As of now, scripts generate data for all available resolutions. 
It might be a good idea to let the user pick what areas of the territory (autonomous regions, or provinces) should be obtained and with what resolution (municipalities or provinces).

**Comment by martgnz** [comment]
This is implemented via https://github.com/martgnz/es-atlas/pull/9 for autonomous regions. I'm satisfied with the current approach, as, at least in my case, I haven't found a project in which I had to filter down to the province level.

Adding province filtering would complicate the script quite a bit and I struggle to see the need for such a niche option (this is all from my point of view, I'm happy to reopen this if there's a strong need for it).

Regarding the different resolution, I think that is fine to return all the files at once, specially now that we have a file for autonomous regions. It doesn't take so much time to run and modify the script if you need to generate just municipalities or provinces.
